# Node.js with Angular

trigger:
- none

parameters:
  - name: environmentName
    type: string
    default: "sandbox"
    displayName: Target Environment
    values:
      - "sandbox"    

variables:
  ${{if eq(parameters.environmentName, 'sandbox')}}:
    rgName: "pkaan_group"
    WebApp: "pkaan"
    serviceConnection: "pkaan_sbx_connection"

stages:
  - stage: Build_App
    displayName: "Build App "
    jobs:
    - job: BuildJob
      pool:
        name: pkaan-selfhost-pool
        vmImage: ubuntu-latest

      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'
      
      - script: |
          npm install -g @angular/cli
        displayName: 'npm install angular/cli'

      - script: |
          npm install
        displayName: 'npm install'

      - script: |
          ng build --configuration production
        displayName: 'ng build'

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/my-app/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/pkaan.zip
          replaceExistingArchive: true
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/pkaan.zip"
          ArtifactName: "drop"
          publishLocation: "Container"
        displayName: "Publish build files"

  - stage: Deploy_app
    displayName: "Deploy app"
    dependsOn: Build_App
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool:
          name: pkaan-selfhost-pool
          vmImage: "ubuntu-latest"
        environment: "${{ parameters.environmentName }} environment"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureWebApp@1
                displayName: 'Deploy Azure Web App : $(WebApp)'
                inputs:
                  azureSubscription: $(serviceConnection)
                  appType: webApp
                  appName: $(WebApp)
                  package: $(Pipeline.Workspace)/drop/pkaan.zip 